### ISSUE TITLE
There is a way to use this app with new version of hipchat? 

### ISSUE THREAD

**Issue by pinheiroalexandre2** [brianc/hipchat-eraser#1]

**Comment by brianc** [comment]
Not really sure...I don't use hipchat anymore.  Definitely down for pull requests or making you a collaborator here if you feel like taking things over. :smile:

**Comment by dbtfree15** [comment]
So it looks like this only goes through the first page.  But now hipchat URLs include page 1, page 2 etc.  For example, it is currently searching: https://somecompany.hipchat.com/history/member/276####/2016/05/20

But that only does page 1 of every day.  For instance, I have page 2 on most conversations, if not more.  For instance:

https://somecompany.hipchat.com/history/member/276####/2016/05/20?p=2
https://somecompany.hipchat.com/history/member/276####/2016/05/20?p=1

Is there any way I can edit your code so that it goes through the pages, like up to page 10 or something?

**Comment by brianc** [comment]
You can definitely edit my code!  Fork the repo, edit to your heart's content.  If you get it working w/ the new hipchat URLs I'd love a pull request back to this repo as well!

**Comment by dbtfree15** [comment]
Cool, will see what I can do.

**Comment by pinheiroalexandre2** [comment]
Close this issue because hipchat has been discontinued.
